export const strings = {
  currency: 'تومان',
  select_variant: 'انتخاب ویژگی',
  weight: 'وزن',
  weight_unit: 'گرم',
  profit: 'اجرت',
  add_to_card: 'افزودن به سبد خرید',
  out_of_stock: 'در انبار موجود نیست',
  pre_order_available: 'امکان پیش سفارش',
  pre_order_invitation: 'این محصول در حال حاضر موجود نیست، اما امکان پیش‌سفارش برای شما فراهم است.',
  cart: 'سبد خرید',
  error_default: 'مشکلی پیش آمده است!',
  error_404: 'صفحه‌ای که دنبال آن بودید پیدا نشد!',
  error_403: 'دسترسی به صفحه مورد نظر امکان پذیر نیست!',
  error_unknown: 'خطایی غیر منتظره پیش آمده است!',
  error_unknown_message: 'لطفا در صورت تکرار با پشتیبانی سایت تماس بگیرید',
  homepage: 'صفحه اصلی',
  priceFilter: 'محدوده قیمت',
  productsFilter: 'فیلتر محصولات',
  errors: {
    invalid_request: 'درخواست معتبر نیست. لطفاً اطلاعات ورودی خود را بررسی کنید.',
    invalid_server_response: 'پاسخ نامعتبر از سرور. لطفاً دوباره تلاش کنید.',
    internal_server_error: 'مشکلی در سرور رخ داده است. لطفاً بعداً دوباره تلاش کنید.',
    validation_error: 'لطفاً خطاهای زیر را برطرف کنید.',
  },
  categoriesFilter: 'فیلتر دسته‌بندی ها',
};
